name: Super-Linter

on:
  pull_request:
    branches: [master, main]

jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_PYTHON_BLACK: true

          FILTER_REGEX_INCLUDE: unassigner/.*|tests/.*|setup.py