name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit