name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  run-tests:
    uses: Ulthran/pycov3/.github/workflows/test.yml@main
    secrets: inherit