name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  run-tests:
    uses: PennChopMicrobiomeProgram/unassigner/.github/workflows/test.yml@master
    secrets: inherit