# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    branches: [master, main]
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.1.0
      with:
        conda-channels: ''
    - name: Install dependencies
      run: |
        conda install -c bioconda vsearch
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests/
